### ISSUE TITLE
How to run finetuning on multiple GPUs?

### ISSUE THREAD

**Issue by Johnson-NLP** [jumon/whisper-finetuning#6]

**Comment by jumon** [comment]
Currently, the code does not support multiple GPU training. However, it is possible to modify the code using DataParallel to achieve it. You can refer to this tutorial on PyTorch's official website for guidance: https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html. 
I plan to create a pull request myself in the future to support multi-GPU training. Thank you for the suggestion!

**Comment by MohamedAliRashad** [comment]
@jumon Any update on this ?
