### ISSUE TITLE
How to get some SRT or VTT data，How do I get the timestamp for each token ？

### ISSUE THREAD

**Issue by daihuangyu** [jumon/whisper-finetuning#7]
I want to run the timestamp finetune whisper，but I dont have any open source SRT or VTT data. Whether the SRT or VTT data were generated using kaldi's align function or something else. Also In my opinion, normal SRT or VTT data only gives a timestamp for each sentence, but this is not consistent with whisper's output of a timestamp for each token. I want to ask the relationship between this, is the training time inconsistent with the inference time？

**Comment by jumon** [comment]
> Whether the SRT or VTT data were generated using kaldi's align function or something else.

If the data you use possess sentence-level timestamps, you can generate SRT files using them. Open-source corpora such as TEDLIUM provide sentence-level timestamps. 

> I want to ask the relationship between this

Whisper is trained using sentence-level timestamps. Recently, the original Whisper repository has introduced a word-level timestamps feature, which is achieved by utilizing attention weights as alignment hints.

**Comment by daihuangyu** [comment]
Thank you for your reply, it completely answered my doubts

**Comment by StephennFernandes** [comment]
Hey is there a dummy dataset that I can perhaps use to test out this implementation. Before i can actually go ahead and train on my own data ? 

@daihuangyu How did you convert your audio dataset into srt vtt format ?
